# Generated by Django 5.1 on 2024-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_category_name_anime_manga_movie_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='title',
            new_name='title_romaji',
        ),
        migrations.AddField(
            model_name='manga',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='average_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='cover_image',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='title_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='title_native',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
