# Generated by Django 5.1 on 2024-10-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_manga_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
