# Generated by Django 5.1 on 2024-10-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_usermangacollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermangacollection',
            name='user_status',
            field=models.CharField(choices=[('finish', 'Finished'), ('currently', 'Currently Reading'), ('pause', 'Paused'), ('to_begin', 'To Begin')], default='to_begin', max_length=20),
        ),
    ]
