# Generated by Django 5.1 on 2024-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_usermangacollection_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermangacollection',
            name='current_chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermangacollection',
            name='user_status',
            field=models.CharField(choices=[('finish', 'Finished'), ('currently', 'Currently Reading'), ('pause', 'Paused'), ('To Begin', 'To Begin')], default='To Begin', max_length=20),
        ),
    ]
