# Generated by Django 5.1 on 2024-10-30 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_usermangacollection_current_chapter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='title',
        ),
        migrations.AddField(
            model_name='anime',
            name='api_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='average_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='cover_image',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='title_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='title_native',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='title_romaji',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermangacollection',
            name='user_status',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Currently Reading', 'Currently Reading'), ('Paused', 'Paused'), ('To Begin', 'To Begin')], default='To Begin', max_length=20),
        ),
    ]
