# Generated by Django 5.1 on 2024-10-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_useranimecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='api_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='backdrop_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='poster_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
