# Generated by Django 5.1 on 2024-10-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_serie_api_id_serie_backdrop_path_serie_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='user',
        ),
    ]
