# Generated by Django 5.1 on 2024-10-30 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_serie_user_userseriecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseriecollection',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.serie'),
        ),
    ]
